### ISSUE TITLE
The split of validation set

### ISSUE THREAD

**Issue by gaunzi** [AutodeskAILab/RobustPointSet#4]
Hi,
Thanks for your contributions for this interesting dataset. Recently, I have tried to reproduce the results  listed in Table1 with the same settings at their original papers. However, the reproduced results are lower(~3 - 4%) than Table1.  And I find that you select the best performing checkpoint on validation set to test, while I select the final trained models to test, which may be the reason. So, could you offer the split of validation set? 
Thanks again. ^_^

**Comment by asgsaeid** [comment]
Hi, thank you for your interest. Please refer to [Strategy 1](https://github.com/AutodeskAILab/RobustPointSet#strategy-1-training-domain-validation) in the updated README.
