### ISSUE TITLE
Regarding provided data

### ISSUE THREAD

**Issue by MukundVarmaT** [AutodeskAILab/RobustPointSet#5]
Hi! Thank you for sharing your work

I had a query regarding the provided data. Since ModelNet40 consists of 10,000 points are the 2048 points selected using farthest point sampling? Also is the provided data already normalized or used as such after sampling from the original dataset? Just to clarify, are all the tests performed on 2048 points?

Thanks :)

**Comment by asgsaeid** [comment]
yes, all the experiments are on 2048 points. For other questions refer to the [preprocessed data](https://shapenet.cs.stanford.edu/media/modelnet40_ply_hdf5_2048.zip) used in the original pointnet repo.
