### ISSUE TITLE
Train and test scripts

### ISSUE THREAD

**Issue by sheshap** [AutodeskAILab/RobustPointSet#8]
Hi,

can you please provide a train and test scripts?
The original benchmarks use .h5 files.
Please let us know how to use .npy files.

Thanks in Advance.

**Comment by asgsaeid** [comment]
Hi, we'll add sample train and test scripts soon. Meanwhile, you can convert numpy files to h5 with the following function. In the following example, `train_original.npy` and `train_labels.npy` can be replaced with other numpy files.

```
import h5py
import numpy as np

data_numpy = np.load('PATH/train_original.npy') 
label_numpy = np.load('PATH/train_labels.npy')


def npy2h5(data, labels, hdf5_filename):
    hdf_file = h5py.File(hdf5_filename, 'w')
    hdf_file.create_dataset('data', dtype=np.float, data=data)
    hdf_file.create_dataset('label', dtype=np.float, data=labels)
    return hdf_file

f = npy2h5(data_numpy, label_numpy, 'train_original.h5')
```

**Comment by asgsaeid** [comment]
Hi, sample codes are now included.
